name: hanoi-tower
version: '1.4.testBuild7' 
summary: Hanoi Towers Game
description: |
  The Hanoi Tower is one of the most popular puzzles of the 19th century. Three bars are given, on one of which eight rings are strung, the rings differ in size and lie smaller on larger ones. The problem is to transfer the pyramid from eight rings for the least number of moves to another rod. At a time, only one ring is allowed to carry, and you can not put a larger ring on less.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

icon: source/res/icon.png

apps:
  hanoi-tower:
    command: qt5-launch opt/hanoi-towers/bin/hanoi-towers
#    desktop: usr/share/applications/desc.desktop
    plugs: [desktop, home, opengl, x11, wayland]


parts:
  hanoi-tower:
    plugin: qmake
    source: source/
    build-packages:
      - qtdeclarative5-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
      - libqt5qml5
      - libqt5quick5
      - qml-module-qtquick2
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-controls2
      - qml-module-qtgraphicaleffects
      - qml-module-qtquick-extras

    after: [qt5conf] # A wiki part


