name: hanoi-tower
version: '1.4.testBuildStatic3' 
summary: Hanoi Towers Game
description: |
  The Hanoi Tower is one of the most popular puzzles of the 19th century. Three bars are given, on one of which eight rings are strung, the rings differ in size and lie smaller on larger ones. The problem is to transfer the pyramid from eight rings for the least number of moves to another rod. At a time, only one ring is allowed to carry, and you can not put a larger ring on less.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

icon: source/res/icon.png

apps:
  hanoi-tower:
    command: bin/hanoi-towers
#    desktop: usr/share/applications/desc.desktop
    plugs: [desktop, unity7, home, opengl, x11, wayland]


parts:
  hanoi-tower:
    plugin: qmake
    source: source/
    stage-packages:
      - libx11-xcb-dev
      - libice-dev
      - libsm-dev
      - libx11-dev
      - libxau-dev
      - libxdmcp-dev
      - libxext-dev
      - libxi-dev
      - libxcb1-dev
    organize:
        opt/hanoi-tower/bin: bin
    after:
      - qt

  qt:
    plugin: qtbuilder
    qt-version: 5.9.4
    qt-source-git: https://code.qt.io/qt/qt5.git
    qt-submodules: ['qtbase', 'qtdeclarative', 'qtsvg', 'qtimageformats', 'qtgraphicaleffects', 'qtquickcontrols', 'qtquickcontrols2', 'qttranslations']

    build-packages:
      - libasound2-dev
      - libdbusmenu-glib-dev
      - libffi-dev
      - liblzma-dev
      - libpulse-dev
      - libssl-dev
      - libx11-xcb-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render-util0-dev
      - libxcb-sync-dev
      - libxcb-util0-dev
      - libxcb-xfixes0-dev
      - libxcb1-dev
      - libxrender-dev
    configflags:
      - -prefix
      - /usr
      - -release
      - -force-debug-info
      - -opensource
      - -confirm-license
      - -qt-zlib
      - -qt-libpng
      - -qt-libjpeg
      - -qt-freetype
      - -qt-harfbuzz
      - -qt-pcre
      - -qt-xcb
      - -qt-xkbcommon-x11
      - -no-opengl
      - -static
      - -dbus-runtime
      - -openssl-linked
      - -nomake
      - examples
      - -nomake
      - tests


