name: hanoi-tower
version: '1.6.0.0'
summary: This game allows you not only to "kill time", it is useful, corrupting logic.
description: |
  This game allows you not only to "kill time", it is useful, corrupting logic. |
  The game is rather a simulator for the development of logical thinking, you can spend time playing at the same time doing self-development. |

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core20
icon: installer/config/logo.png

apps:
  hanoi-tower:
    command: bin/desktop-launch $SNAP/HanoiTowers.sh
    plugs: [desktop, unity7, home, opengl, x11, wayland, gsettings]

parts:
  hanoi-tower:
    plugin: nil
    stage-packages:
      - libasn1-8-heimdal
      - libgssapi3-heimdal
      - libldap-2.4-2
    after: [libsgl, qtlib, desktop-qt5]

    override-prime: |
      chmod 777 -R "$SNAPCRAFT_PRIME"
      snapcraftctl prime

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make

  qtlib:
    plugin: dump
    source: Distro/HanoiTowers.zip

  libsgl:
    plugin: nil
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libx11-xcb1
      - libglu1-mesa
      - libxrender1
      - libxi6
      - libegl1-mesa
      - fontconfig
      - libgl1-mesa-dri
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - libgtk2.0-0
      - xdg-user-dirs
      - libxrandr2
      - libwayland-cursor0
      - libwayland-egl1
      - libpq5
